### PR TITLE
appveyor: Add code coverage CI config

### PR DESCRIPTION
**Pull request by jvesely**
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

### CODE REVIEW

**Comment by jvesely** [comment]
While the config can run on appveyor's could runners, it takes too long (more than the max time allowed by appveyor).

**Comment by jvesely** [comment]
@kmantel, this one has been blocked on https://ci.appveyor.com/project/kmantel/psyneulink
Is it needed? has it ever worked? pnl test suite has been too big for appveyor cloud instances for some time.

**Comment by kmantel** [comment]
I can't remember why the project under my account is there - it doesn't even look to be running regularly, even just timing out. The one under your account looks to be running though, despite the appveyor config being removed in #1571. I guess it's configured totally on the appveyor site and running on ?Yale? machines? 

If https://ci.appveyor.com/project/kmantel/psyneulink is the problem I'm ok with deleting or disabling it.

**Comment by jvesely** [comment]
> I can't remember why the project under my account is there - it doesn't even look to be running regularly, even just timing out. The one under your account looks to be running though, despite the appveyor config being removed in #1571. I guess it's configured totally on the appveyor site and running on ?Yale? machines?
> 
> If https://ci.appveyor.com/project/kmantel/psyneulink is the problem I'm ok with deleting or disabling it.

yes. the config is completely in the appveyor project now. this PR moves most of it to the .appveyor.cfg config file. the part that remains in the appveyor project config is selecting a private cloud to run these workflows.

I don't mind keeping https://ci.appveyor.com/project/kmantel/psyneulink alive, but if it aims to run PNL code coverage workflow it will need private runners.

**Comment by kmantel** [comment]
>yes. the config is completely in the appveyor project now. this PR moves most of it to the .appveyor.cfg config file

Ok, then it makes sense that it's only started running on this PR. I've disabled the webhook and what I could on my project, so I think it should be disabled now.

**Pull request merged**
