### PR TITLE
deps: Add leabra as dependency to PsyNeuLink

### PR DESCRIPTION
**Pull request by dillontsmith**
Add `leabra` to `requirements.txt` and remove special casing from before the package was on PyPi

### CODE REVIEW

**Comment by jvesely** [comment]
This needs CI changes similar to #1815

**Comment by dillontsmith** [comment]
@jvesely, I was under the impression that the CI changes from #1815 were needed because the leabra requirement was 1) a direct dependency and 2) in a separate requirements file. Is this not the case?

**Comment by dillontsmith** [comment]
retest this please

**Comment by jvesely** [comment]
> @jvesely, I was under the impression that the CI changes from #1815 were needed because the leabra requirement was 1) a direct dependency and 2) in a separate requirements file. Is this not the case?

My understanding was that leabra-psyneulink replaces git+https://github.com/benureau/leabra.git@master
if so, 1.) should still be applied here. if leabra is pulled via a dependency file, the direct pip install from git should be removed from CI setup.

PS: I'd expect leabra-psyneulink and leabra.git to conflict on install since they both add 'leabra' module. wonder how both of them coexist.

**Comment by dillontsmith** [comment]
Ah, I see. You're right, on this pull the CI is redundantly installing the original leabra package + the one on PyPi. Will upload a patch to fix.

**Comment by jvesely** [comment]
> Ah, I see. You're right, on this pull the CI is redundantly installing the original leabra package + the one on PyPi. Will upload a patch to fix.
> 
> Edit: patched in [7a161e6](https://github.com/PrincetonUniversity/PsyNeuLink/commit/7a161e619307a6bc159b8500995596efadee7a05)

thanks. LGTM

**Comment by dillontsmith** [comment]
retest this please

**Comment by dillontsmith** [comment]
retest this please

**Pull request merged**
