### PR TITLE
Fix/llvm/num trials bug

### PR DESCRIPTION
**Pull request by SamKG**
Fixes a few bugs related to correctness and does some small cleanup

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by dillontsmith** [comment]
ok to test

**Comment by dillontsmith** [comment]
Ok to test

**Comment by jvesely** [comment]
ok to test

**Pull request merged**
