### PR TITLE
Implement EpisodicMemoryMechanism and co

### PR DESCRIPTION
**Pull request by jvesely**
Implement COSINE metric for Distance function.
Implement OneHot function.
Implement DND memory function.
Implement EpisodicMemoryMechanism.
Add pytest for bistable percepts.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by jvesely** [comment]
add to whitelist

**Comment by jvesely** [comment]
ok to test

**Comment by jvesely** [comment]
add to whitelist

**Pull request merged**
