### PR TITLE
Drop support for Python 3.6

### PR DESCRIPTION
**Pull request by jvesely**
Drop python 3.6 CI jobs.
Bump python requirement.

### CODE REVIEW

**Comment by jvesely** [comment]
I've tested that the CI (including the release script works).

https://github.com/jvesely/PsyNeuLink/actions/runs/875922224

**Review by kmantel — APPROVED** [review]
One reason is numpy dropping support for 3.6, any others in particular? Anyway, I moved the required CI status to jenkins 3.7 so this can go through.

**Comment by jvesely** [comment]
> One reason is numpy dropping support for 3.6, any others in particular? Anyway, I moved the required CI status to jenkins 3.7 so this can go through.

I think it was a more generic "support the last 3 versions of python" thing.
Python 3.6 EOL date is Dec 2021 and has been providing source-only releases for some time.

Linux and Windows can easily install a newer version from the package managers.
I don't really know how difficult it is to maintain up-to-date Python on mac.

This PR can wait until December, but I don't see any benefit at the cost of more CI jobs.

**Comment by jvesely** [comment]
retest this please

**Comment by jvesely** [comment]
looks like the pytest-3.6 job needs to be disabled entirely for this PR to go ahead

**Pull request merged**
