### PR TITLE
requirements: Update numpy to <1.22.5

### PR DESCRIPTION
**Pull request by jvesely**
Do not check for string values of numpy errors.
Refactor exception handling to check only calls to 'execute'.

### CODE REVIEW

**Review by kmantel — APPROVED** [review]
lgtm, doesn't seem critical to have the exact numpy error text not change

**Comment by jvesely** [comment]
> lgtm, doesn't seem critical to have the exact numpy error text not change

thank you.
It looks like 1.22 is also hitting some numerical issues which I thought were introduced in 1.23 (this PR passes locally on my Linux setup).
I'll keep this open and rebase after investigating those.

**Comment by jvesely** [comment]
@dependabot rebase

**Comment by jvesely** [comment]
> > lgtm, doesn't seem critical to have the exact numpy error text not change
> 
> thank you. It looks like 1.22 is also hitting some numerical issues which I thought were introduced in 1.23 (this PR passes locally on my Linux setup). I'll keep this open and rebase after investigating those.

the issues are now tracked in #2572

**Comment by jvesely** [comment]
Ignoring results of the x86 CI job. It can't uninstall numpy because it was installed in the restricted package set one step earlier.

**Pull request merged**
