### PR TITLE
ga: Move wheel/sdist creation to install-pnl action

### PR DESCRIPTION
**Pull request by jvesely**
Use wheel package to install psyneulink instead of using editable install.
Provide paths in install-pnl action outputs.
Use install-pnl outputs to upload the hwheel/sdist.

### CODE REVIEW

**Comment by jvesely** [comment]
This passes CI but still has issues.
Issue 1:
The root_dir cannot be set in `_version.py`
show graph doesn't work:
```
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/core/globals/context.py", line 742, in wrapper
    return func(*args, context=context, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/core/compositions/composition.py", line 11670, in learn
    result = runner.run_learning(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/library/compositions/compositionrunner.py", line 348, in run_learning
    self._composition.run(inputs=minibatched_input,
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/core/globals/context.py", line 742, in wrapper
    return func(*args, context=context, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/core/compositions/composition.py", line 11209, in run
    self._set_up_animation(context)
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/core/compositions/composition.py", line 13668, in _set_up_animation
    self._show_graph._set_up_animation(context)
  File "/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/core/compositions/showgraph.py", line 2816, in _set_up_animation
    from psyneulink._version import root_dir
ImportError: cannot import name 'root_dir' from 'psyneulink._version' (/home/runner/work/_temp/_venv/lib/python3.11/site-packages/psyneulink/_version.py)
```
This is because _version gets updated when generating sdist or wheel:
```
...
copying tutorial/PsyNeuLink Tutorial.ipynb -> psyneulink-0.15.1.0+376.gf5f8f2d348/tutorial
copying psyneulink.egg-info/SOURCES.txt -> psyneulink-0.15.1.0+376.gf5f8f2d348/psyneulink.egg-info
Writing psyneulink-0.15.1.0+376.gf5f8f2d348/setup.cfg
UPDATING psyneulink-0.15.1.0+376.gf5f8f2d348/psyneulink/_version.py
set psyneulink-0.15.1.0+376.gf5f8f2d348/psyneulink/_version.py to '0.15.1.0+376.gf5f8f2d348'
creating dist
Creating tar archive
removing 'psyneulink-0.15.1.0+376.gf5f8f2d348' (and everything under it)
```

2.
We cannot use `root_dir` to store any generated files.
The above is good, the root would resolve to `.../lib/python3.11/site-packages/psyneulink/` or something similar. We definitely shouldn't save test-generated files there.

**Comment by jvesely** [comment]
3. is now addressed in https://github.com/PrincetonUniversity/PsyNeuLink/pull/3087

**Comment by kmantel** [comment]
Does 2 break this also, or is it just not great to have the files there? Anyway, it's not harder to just do both - root_dir is only used in the one place in showgraph.py, and it can be determined as needed, avoiding the site-packages dir if pnl is installed there.

**Comment by jvesely** [comment]
> Does 2 break this also, or is it just not great to have the files there? Anyway, it's not harder to just do both - root_dir is only used in the one place in showgraph.py, and it can be determined as needed, avoiding the site-packages dir if pnl is installed there.

The installation directory can be in the system root (e.g., `/usr/lib64/Python3.11/site-packages`), which we don't have permission to write to. Even if we do have permissions (e.g., `~/pnl-venv/lib64/Python3.11/site-packages`), it's not a user-friendly location to put generated files.

**Review by kmantel — APPROVED** [review]

**Pull request merged**
