### PR TITLE
travis: Don't run or install coveralls if the repo token is not set

### PR DESCRIPTION
**Pull request by jvesely**
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by jvesely** [comment]
This saves 10+minutes on travis runs without coveralls.

**Pull request merged**
