### PR TITLE
requirements: Move doc requirements to a separate file

### PR DESCRIPTION
**Pull request by jvesely**
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

### CODE REVIEW

**Review by kmantel — APPROVED** [review]
Looks fine. We'll need to update the jenkins build scripts to install the doc requirements.

**Comment by jvesely** [comment]
> Looks fine. We'll need to update the jenkins build scripts to install the doc requirements.

does jenkins build docs as part of CI run?

**Comment by kmantel** [comment]
> > Looks fine. We'll need to update the jenkins build scripts to install the doc requirements.
> 
> does jenkins build docs as part of CI run?
> let me know when it's safe to merge.

There's a separate job for it that runs for devel/master but doesn't report status. pip install allows undefined extras so it should ready for this change now.

**Comment by jvesely** [comment]
> > > Looks fine. We'll need to update the jenkins build scripts to install the doc requirements.
> > 
> > 
> > does jenkins build docs as part of CI run?
> > let me know when it's safe to merge.
> 
> There's a separate job for it that runs for devel/master but doesn't report status. pip install allows undefined extras so it should ready for this change now.

thanks! is it worth converting it to github-actions at some point in ehte future?

**Comment by kmantel** [comment]
> thanks! is it worth converting it to github-actions at some point in the future?

Yeah it could be, the docs are hosted on github pages anyway.

**Pull request merged**
