### PR TITLE
docs: Fix basic rst formatting errors

### PR DESCRIPTION
**Pull request by jvesely**
Fix the following warnings:
WARNING: Malformed table. (3 instances)
WARNING: Title underline too short. (13 instances)
WARNING: Inline strong start-string without end-string. (31 instances)
WARNING: Inline literal start-string without end-string. (1 instance)
WARNING: Inline emphasis start-string without end-string. (2 instances)
WARNING: Unknown target name (3 instances)
WARNING: Inline interpreted text or phrase reference start-string without end-string. (31 instances)
WARNING: Inline substitution_reference start-string without end-string. (1 instance)

The above removes 61/81 instances of `<span class="problematic">` in the generated html.

### CODE REVIEW

**Comment by jvesely** [comment]
The remaining 20 issues causing "problematic"  are in the following files:
```
build/html/Condition.html
build/html/Defaults.html
build/html/globals.html
build/html/nback_nb.html
```

`build/html/Condition.html` -- should be fixable in the graph_scheduler package.
`build/html/Defaults.html` and `build/html/globals.html` -- an experiment in printing the value of defaultAllocation
`build/html/nback_nb.html` -- misrepresented python code in notebook.

**Comment by jvesely** [comment]
The HTML documentation with the fixes is available at [0]
e.g. the malformed table in "Comparison of learning modes" is absent from the documentation [1], but it is displayed correctly after the fixes are applied [2].

[0]  https://jvesely.github.io/PsyNeuLink/branch/docs/
[1] https://princetonuniversity.github.io/PsyNeuLink/Composition.html#comparison-of-learning-modes
[2] https://princetonuniversity.github.io/PsyNeuLink/Composition.html#comparison-of-learning-modes

**Review by kmantel — APPROVED** [review]
Looks good. 

I'll try to fix the problems with `build/html/Condition.html`. 

Did you notice these just looking through the warning messages on a build or did you see the missing table in the docs?

**Comment by jvesely** [comment]
> Looks good.
> 
> I'll try to fix the problems with `build/html/Condition.html`.
> 
> Did you notice these just looking through the warning messages on a build or did you see the missing table in the docs?

Thank you.
I started looking at the warning stats from logs (`grep 'WARNING: [^ ][^ ]* [^ ][^ ]*' -o docs/0_base.log  | sort | uniq -c`) and tried to fix a few low-count instances. (e.g. `3 WARNING: Malformed table.`) Then I noticed the HTML diff and the fact that `class="problematic"` was removed so I focused on those.
I didn't find a way to selectively turn some warnings into errors to prevent reintroducing them later.

The current warnings count is:
```
   1591 WARNING: 'any' reference
      6 WARNING: autodoc: failed
    112 WARNING: Block quote
    171 WARNING: Bullet list
     32 WARNING: Cannot resolve
      2 WARNING: circular toctree
      5 WARNING: Content block
      3 WARNING: Could not
     33 WARNING: Definition list
     19 WARNING: document isn't
      3 WARNING: download file
      9 WARNING: Duplicate explicit
     16 WARNING: duplicate label
     62 WARNING: duplicate object
    149 WARNING: Explicit markup
      2 WARNING: Field list
      1 WARNING: Figure caption
      1 WARNING: image file
     14 WARNING: Inline emphasis
      6 WARNING: Inline strong
      8 WARNING: Line block
      6 WARNING: Literal block
     15 WARNING: malformed hyperlink
      3 WARNING: missing attribute
   2861 WARNING: more than
      4 WARNING: toctree contains
      1 WARNING: undefined label:
      1 WARNING: Undefined substitution
    157 WARNING: Unexpected indentation.
     11 WARNING: Unexpected section
      1 WARNING: Unknown interpreted
     23 WARNING: unknown keyword:
```

**Pull request merged**
