### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by dillontsmith**

### CODE REVIEW

**Comment by jvesely** [comment]
Should we fix the incorrect parameter names before merging?

**Comment by jdcpni** [comment]
Sorry, haven’t been tracking.  Which names?


jdc



On Jun 23, 2020, at 11:30 AM, Jan Vesely <notifications@github.com<mailto:notifications@github.com>> wrote:



Should we fix the incorrect parameter names before merging?

**Comment by jvesely** [comment]
> Sorry, haven’t been tracking. Which names? jdc

The LGTM static analysis results above indicate calls to `show_graph` from examples that use non-existent parameters.
One looks like a typo `Keyword argument 'show_nesed' is not a supported parameter name of method Composition.show_graph.`
The rest look like something that was removed `Keyword argument 'show_model_based_optimizer' is not a supported parameter name of method Composition.show_graph.`

**Comment by dillontsmith** [comment]
> > Sorry, haven’t been tracking. Which names? jdc
> 
> The LGTM static analysis results above indicate calls to `show_graph` from examples that use non-existent parameters.
> One looks like a typo `Keyword argument 'show_nesed' is not a supported parameter name of method Composition.show_graph.`
> The rest look like something that was removed `Keyword argument 'show_model_based_optimizer' is not a supported parameter name of method Composition.show_graph.`

I'll fix the broken references and then merge

**Pull request merged**
