### PR TITLE
Fix compiled printf

### PR DESCRIPTION
**Pull request by SamKG**
@jvesely 
This pull fixes compiled printf by reverting it to the original version, and also adds extra test cases to better check for correctness.

There is a bug with the live version in which varargs are not correctly passed to the builtin printf wrapper

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by jvesely** [comment]
ok to test

**Comment by jvesely** [comment]
add to whitelist

**Pull request merged**
